export const GET_CART_REQUEST="GET_CART_REQUEST"
export const GET_CART_SUCCESS="GET_CART_SUCCESS"
export const GET_CART_FAIL="GET_CART_FAIL"

export const ADD_CART_REQUEST="ADD_CART_REQUEST"
export const ADD_CART_SUCCESS="ADD_CART_SUCCESS"
export const ADD_CART_FAIL="ADD_CART_FAIL"

export const REMOVE_CART_REQUEST="REMOVE_CART_REQUEST"
export const REMOVE_CART_SUCCESS="REMOVE_CART_SUCCESS"
export const REMOVE_CART_FAIL="REMOVE_CART_FAIL"

export const ADJUST_CART_REQUEST="ADJUST_CART_REQUEST"
export const ADJUST_CART_SUCCESS="ADJUST_CART_SUCCESS"
export const ADJUST_CART_FAIL="ADJUST_CART_FAIL"
